apiVersion: sources.knative.dev/v1beta1
kind: ContainerSource
metadata:
  name: twitter-test
  annotations:
    traffic.sidecar.istio.io/includeOutboundIPRanges: "INCLUDE_OUTBOUND_IPRANGES"
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  template:
    spec:
      containers:
      - image: ko://github.com/vaikas/twitter/cmd/source
        args:
        - --query=QUERY
        - --stream=true
        env:
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: consumer-key
        - name: TWITTER_CONSUMER_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: consumer-secret-key
        - name: TWITTER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: access-token
        - name: TWITTER_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: access-secret
